
    env {
      parallelism = 1
    }
    source {
      Oracle {
        table = "CUSTOMER"
        result_table_name = "src_cust"
      }
    }
    sink {
      Jdbc {
        source_table_name = "src_cust"
        table = "customer"
      }
    }
    