
source {
  Oracle {
    table = "SALARIES"
    result_table_name = "src_sal"
  }
}
transform {
  Sql {
    source_table_name = "src_sal"
    result_table_name = "sink_sal"
    query = "SELECT EMP_ID, SALARY, BONUS FROM src_sal"
  }
}
sink {
  Jdbc {
    source_table_name = "sink_sal"
    table = "salaries"
  }
}
