#!/usr/bin/env python3
"""
build_dvt_config.py — Stage 1 preflight step 3: generate a DVT validation
config YAML that reuses the Stage-1 contract.

This does NOT run DVT.  It only writes the YAML that Stage 2 would consume
once both databases are connected.

Output (generated/):
  dvt_validation_config.yaml
"""

import json, sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
GENERATED = BASE / "generated"


def build(manifest: dict) -> str:
    lines = []
    lines.append("# DVT validation config — generated by Stage-1 preflight")
    lines.append("# Do not edit by hand; re-run scripts/run_preflight.py")
    lines.append("")
    lines.append("sources:")
    lines.append("  oracle:")
    lines.append("    type: oracle")
    lines.append("    connection: ${ORACLE_JDBC_URL}")
    lines.append("    user: ${ORACLE_DB_USER}")
    lines.append("    password: ${ORACLE_DB_PASSWORD}")
    lines.append("  postgresql:")
    lines.append("    type: postgresql")
    lines.append("    connection: ${PG_JDBC_URL}")
    lines.append("    user: ${PG_DB_USER}")
    lines.append("    password: ${PG_DB_PASSWORD}")
    lines.append("")
    lines.append("convention:")
    lines.append("  zero_rows_means_pass: true")
    lines.append("  nonzero_rows_means_fail: true")
    lines.append("")
    lines.append("validations:")

    for entry in manifest["jobs"]:
        job_id = entry["job_id"]
        d = entry.get("duckdb") or {}
        if not d:
            continue
        checks = d.get("checks", [])
        sql_checks = [c for c in checks if c.get("sql")]

        lines.append(f"  - name: {job_id}")
        lines.append(f"    source: \"{d.get('target_relation', '')}\"")
        lines.append(f"    target: \"{d.get('target_relation', '')}\"")
        lines.append(f"    run_scn: ${{RUN_RECORD_ORACLE_SCN}}")
        lines.append(f"    checks:")
        for c in sql_checks:
            cid = c["check_id"]
            ctype = c["type"]
            sql = c["sql"].replace('\n', ' ').strip()
            lines.append(f"      - id: {cid}")
            lines.append(f"        type: {ctype}")
            lines.append(f"        sql: \"{sql}\"")
        if not sql_checks:
            lines.append("      # runtime-only checks — see duckdb.yaml")
        lines.append("")

    return "\n".join(lines)


def main():
    with open(GENERATED / "jobs.json") as f:
        manifest = json.load(f)

    yaml_text = build(manifest)
    out = GENERATED / "dvt_validation_config.yaml"
    out.write_text(yaml_text)

    # Count validations written
    n = sum(1 for e in manifest["jobs"] if e.get("duckdb"))
    print(f"Wrote DVT config for {n} jobs → {out}")
    print("Connection details are env-var based; no secrets in this file.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
