-- ============================================================================
-- Oracle Sample Demo Data Setup Script
-- Schema: SPORTS
-- Tables: CUSTOMERS, PRODUCTS, ORDERS, ORDER_ITEMS, PAYMENTS, INVENTORY
-- ============================================================================

-- 1. Create User/Schema if not already created
-- (Run as SYSTEM or administrative user in FREEPDB1)
ALTER SESSION SET CONTAINER = FREEPDB1;

BEGIN
   EXECUTE IMMEDIATE 'CREATE USER SPORTS IDENTIFIED BY root12345 DEFAULT TABLESPACE users QUOTA UNLIMITED ON users';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -01920 THEN -- Ignore "user already exists"
         NULL;
      END IF;
END;
/

GRANT CONNECT, RESOURCE, DBA TO SPORTS;
GRANT UNLIMITED TABLESPACE TO SPORTS;

-- Switch session to SPORTS schema
ALTER SESSION SET CURRENT_SCHEMA = SPORTS;

-- 2. Drop existing tables if re-running
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SPORTS.PAYMENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SPORTS.ORDER_ITEMS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SPORTS.ORDERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SPORTS.INVENTORY CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SPORTS.PRODUCTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SPORTS.CUSTOMERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ============================================================================
-- 3. Create Tables
-- ============================================================================

CREATE TABLE SPORTS.CUSTOMERS (
    CUSTOMER_ID   NUMBER PRIMARY KEY,
    FIRST_NAME    VARCHAR2(50),
    LAST_NAME     VARCHAR2(50),
    EMAIL         VARCHAR2(100),
    PHONE         VARCHAR2(30),
    ADDRESS       VARCHAR2(200),
    CITY          VARCHAR2(50),
    STATE         VARCHAR2(50),
    POSTAL_CODE   VARCHAR2(20),
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SPORTS.PRODUCTS (
    PRODUCT_ID    NUMBER PRIMARY KEY,
    PRODUCT_NAME  VARCHAR2(100),
    CATEGORY_ID   NUMBER,
    BRAND         VARCHAR2(50),
    PRICE         NUMBER(10, 2),
    DESCRIPTION   VARCHAR2(255),
    "SIZE"        VARCHAR2(20),
    COLOR         VARCHAR2(30),
    ACTIVE        NUMBER(1) DEFAULT 1,
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SPORTS.ORDERS (
    ORDER_ID         NUMBER PRIMARY KEY,
    CUSTOMER_ID      NUMBER,
    ORDER_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOTAL_AMOUNT     NUMBER(10, 2),
    STATUS           VARCHAR2(30),
    SHIPPING_ADDRESS VARCHAR2(200),
    CONSTRAINT fk_order_cust FOREIGN KEY (CUSTOMER_ID) REFERENCES SPORTS.CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE SPORTS.ORDER_ITEMS (
    ORDER_ITEM_ID  NUMBER PRIMARY KEY,
    ORDER_ID       NUMBER,
    PRODUCT_ID     NUMBER,
    QUANTITY       NUMBER,
    UNIT_PRICE     NUMBER(10, 2),
    DISCOUNT       NUMBER(10, 2) DEFAULT 0.00,
    CONSTRAINT fk_item_order FOREIGN KEY (ORDER_ID) REFERENCES SPORTS.ORDERS(ORDER_ID),
    CONSTRAINT fk_item_prod FOREIGN KEY (PRODUCT_ID) REFERENCES SPORTS.PRODUCTS(PRODUCT_ID)
);

CREATE TABLE SPORTS.PAYMENTS (
    PAYMENT_ID      NUMBER PRIMARY KEY,
    ORDER_ID        NUMBER,
    PAYMENT_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AMOUNT          NUMBER(10, 2),
    PAYMENT_METHOD  VARCHAR2(50),
    PAYMENT_STATUS  VARCHAR2(30),
    TRANSACTION_ID  VARCHAR2(100),
    CONSTRAINT fk_pay_order FOREIGN KEY (ORDER_ID) REFERENCES SPORTS.ORDERS(ORDER_ID)
);

CREATE TABLE SPORTS.INVENTORY (
    INVENTORY_ID   NUMBER PRIMARY KEY,
    PRODUCT_ID     NUMBER,
    STOCK_QTY      NUMBER,
    REORDER_LEVEL  NUMBER,
    UPDATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inv_prod FOREIGN KEY (PRODUCT_ID) REFERENCES SPORTS.PRODUCTS(PRODUCT_ID)
);

-- ============================================================================
-- 4. Insert Demo Data
-- ============================================================================

-- Customers
INSERT INTO SPORTS.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, POSTAL_CODE, CREATED_AT)
VALUES (1, 'John', 'Doe', 'john.doe@example.com', '+1-555-0101', '100 Main St', 'New York', 'NY', '10001', TIMESTAMP '2026-01-10 10:00:00');

INSERT INTO SPORTS.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, POSTAL_CODE, CREATED_AT)
VALUES (2, 'Jane', 'Smith', 'jane.smith@example.com', '+1-555-0102', '200 Oak Ave', 'Los Angeles', 'CA', '90001', TIMESTAMP '2026-01-12 11:30:00');

INSERT INTO SPORTS.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, POSTAL_CODE, CREATED_AT)
VALUES (3, 'Michael', 'Johnson', 'michael.j@example.com', '+1-555-0103', '300 Pine Rd', 'Chicago', 'IL', '60601', TIMESTAMP '2026-02-01 09:15:00');

INSERT INTO SPORTS.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, POSTAL_CODE, CREATED_AT)
VALUES (4, 'Emily', 'Davis', 'emily.d@example.com', '+1-555-0104', '400 Elm St', 'Houston', 'TX', '77001', TIMESTAMP '2026-02-15 14:45:00');

INSERT INTO SPORTS.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, POSTAL_CODE, CREATED_AT)
VALUES (5, 'David', 'Brown', 'david.b@example.com', '+1-555-0105', '500 Maple Dr', 'Miami', 'FL', '33101', TIMESTAMP '2026-03-01 16:20:00');

-- Products
INSERT INTO SPORTS.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, BRAND, PRICE, DESCRIPTION, "SIZE", COLOR, ACTIVE, CREATED_AT)
VALUES (101, 'Running Pro Shoes', 1, 'Nike', 120.00, 'Breathable road running shoes', '10', 'Black/Red', 1, TIMESTAMP '2026-01-05 08:00:00');

INSERT INTO SPORTS.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, BRAND, PRICE, DESCRIPTION, "SIZE", COLOR, ACTIVE, CREATED_AT)
VALUES (102, 'Soccer Match Ball', 2, 'Adidas', 45.50, 'FIFA certified training soccer ball', '5', 'White/Blue', 1, TIMESTAMP '2026-01-05 08:30:00');

INSERT INTO SPORTS.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, BRAND, PRICE, DESCRIPTION, "SIZE", COLOR, ACTIVE, CREATED_AT)
VALUES (103, 'Performance Dri-FIT Shirt', 3, 'Under Armour', 35.00, 'Moisture-wicking athletic tee', 'L', 'Navy', 1, TIMESTAMP '2026-01-06 10:00:00');

INSERT INTO SPORTS.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, BRAND, PRICE, DESCRIPTION, "SIZE", COLOR, ACTIVE, CREATED_AT)
VALUES (104, 'Basketball Grip Elite', 2, 'Wilson', 60.00, 'Indoor composite leather basketball', '7', 'Orange', 1, TIMESTAMP '2026-01-07 11:00:00');

INSERT INTO SPORTS.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, BRAND, PRICE, DESCRIPTION, "SIZE", COLOR, ACTIVE, CREATED_AT)
VALUES (105, 'Fitness Water Bottle 1L', 4, 'HydroFlask', 25.00, 'Insulated stainless steel sports bottle', '1L', 'Silver', 1, TIMESTAMP '2026-01-08 12:00:00');

-- Orders
INSERT INTO SPORTS.ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, STATUS, SHIPPING_ADDRESS)
VALUES (1001, 1, TIMESTAMP '2026-02-10 14:00:00', 165.50, 'COMPLETED', '100 Main St, New York, NY 10001');

INSERT INTO SPORTS.ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, STATUS, SHIPPING_ADDRESS)
VALUES (1002, 2, TIMESTAMP '2026-02-12 15:30:00', 120.00, 'COMPLETED', '200 Oak Ave, Los Angeles, CA 90001');

INSERT INTO SPORTS.ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, STATUS, SHIPPING_ADDRESS)
VALUES (1003, 3, TIMESTAMP '2026-02-14 11:15:00', 70.00, 'PROCESSING', '300 Pine Rd, Chicago, IL 60601');

INSERT INTO SPORTS.ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, STATUS, SHIPPING_ADDRESS)
VALUES (1004, 4, TIMESTAMP '2026-02-18 16:45:00', 60.00, 'COMPLETED', '400 Elm St, Houston, TX 77001');

INSERT INTO SPORTS.ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, STATUS, SHIPPING_ADDRESS)
VALUES (1005, 5, TIMESTAMP '2026-02-20 10:20:00', 145.00, 'SHIPPED', '500 Maple Dr, Miami, FL 33101');

-- Order Items
INSERT INTO SPORTS.ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, DISCOUNT)
VALUES (5001, 1001, 101, 1, 120.00, 0.00);

INSERT INTO SPORTS.ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, DISCOUNT)
VALUES (5002, 1001, 102, 1, 45.50, 0.00);

INSERT INTO SPORTS.ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, DISCOUNT)
VALUES (5003, 1002, 101, 1, 120.00, 0.00);

INSERT INTO SPORTS.ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, DISCOUNT)
VALUES (5004, 1003, 103, 2, 35.00, 0.00);

INSERT INTO SPORTS.ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, DISCOUNT)
VALUES (5005, 1004, 104, 1, 60.00, 0.00);

INSERT INTO SPORTS.ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, DISCOUNT)
VALUES (5006, 1005, 101, 1, 120.00, 0.00);

INSERT INTO SPORTS.ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, DISCOUNT)
VALUES (5007, 1005, 105, 1, 25.00, 0.00);

-- Payments
INSERT INTO SPORTS.PAYMENTS (PAYMENT_ID, ORDER_ID, PAYMENT_DATE, AMOUNT, PAYMENT_METHOD, PAYMENT_STATUS, TRANSACTION_ID)
VALUES (9001, 1001, TIMESTAMP '2026-02-10 14:05:00', 165.50, 'CREDIT_CARD', 'SUCCESS', 'TXN-98127391');

INSERT INTO SPORTS.PAYMENTS (PAYMENT_ID, ORDER_ID, PAYMENT_DATE, AMOUNT, PAYMENT_METHOD, PAYMENT_STATUS, TRANSACTION_ID)
VALUES (9002, 1002, TIMESTAMP '2026-02-12 15:35:00', 120.00, 'PAYPAL', 'SUCCESS', 'TXN-98127392');

INSERT INTO SPORTS.PAYMENTS (PAYMENT_ID, ORDER_ID, PAYMENT_DATE, AMOUNT, PAYMENT_METHOD, PAYMENT_STATUS, TRANSACTION_ID)
VALUES (9003, 1003, TIMESTAMP '2026-02-14 11:20:00', 70.00, 'DEBIT_CARD', 'PENDING', 'TXN-98127393');

INSERT INTO SPORTS.PAYMENTS (PAYMENT_ID, ORDER_ID, PAYMENT_DATE, AMOUNT, PAYMENT_METHOD, PAYMENT_STATUS, TRANSACTION_ID)
VALUES (9004, 1004, TIMESTAMP '2026-02-18 16:50:00', 60.00, 'CREDIT_CARD', 'SUCCESS', 'TXN-98127394');

INSERT INTO SPORTS.PAYMENTS (PAYMENT_ID, ORDER_ID, PAYMENT_DATE, AMOUNT, PAYMENT_METHOD, PAYMENT_STATUS, TRANSACTION_ID)
VALUES (9005, 1005, TIMESTAMP '2026-02-20 10:25:00', 145.00, 'APPLE_PAY', 'SUCCESS', 'TXN-98127395');

-- Inventory
INSERT INTO SPORTS.INVENTORY (INVENTORY_ID, PRODUCT_ID, STOCK_QTY, REORDER_LEVEL, UPDATED_AT)
VALUES (701, 101, 50, 10, TIMESTAMP '2026-03-01 08:00:00');

INSERT INTO SPORTS.INVENTORY (INVENTORY_ID, PRODUCT_ID, STOCK_QTY, REORDER_LEVEL, UPDATED_AT)
VALUES (702, 102, 85, 15, TIMESTAMP '2026-03-01 08:00:00');

INSERT INTO SPORTS.INVENTORY (INVENTORY_ID, PRODUCT_ID, STOCK_QTY, REORDER_LEVEL, UPDATED_AT)
VALUES (703, 103, 120, 25, TIMESTAMP '2026-03-01 08:00:00');

INSERT INTO SPORTS.INVENTORY (INVENTORY_ID, PRODUCT_ID, STOCK_QTY, REORDER_LEVEL, UPDATED_AT)
VALUES (704, 104, 40, 10, TIMESTAMP '2026-03-01 08:00:00');

INSERT INTO SPORTS.INVENTORY (INVENTORY_ID, PRODUCT_ID, STOCK_QTY, REORDER_LEVEL, UPDATED_AT)
VALUES (705, 105, 200, 30, TIMESTAMP '2026-03-01 08:00:00');

COMMIT;
