
env {
  parallelism = 1
}
source {
  Oracle {
    table = "EMPLOYEES"
    result_table_name = "src_emp"
  }
}
transform {
  Sql {
    source_table_name = "src_emp"
    result_table_name = "sink_emp"
    query = "SELECT EMP_ID AS emp_id, FIRST_NAME AS first_name, SALARY AS salary FROM src_emp"
  }
}
sink {
  Jdbc {
    source_table_name = "sink_emp"
    table = "public.employees"
  }
}
