
    env {
      parallelism = 1
    }
    source {
      Oracle {
        table = "CUSTOMER"
        result_table_name = "src_cust"
      }
    }
    transform {
      Sql {
        source_table_name = "src_cust"
        result_table_name = "sink_cust"
        query = "SELECT ID AS id, NAME AS name FROM src_cust"
      }
    }
    sink {
      Jdbc {
        source_table_name = "sink_cust"
        table = "customer"
      }
    }
    