
env {
  parallelism = 1
}
source {
  Oracle-CDC {
    schema-name = "HR_APP"
    table-name = "DEPARTMENTS"
    result_table_name = "src_dept"
  }
}
transform {
  Sql {
    source_table_name = "src_dept"
    result_table_name = "sink_dept"
    query = "SELECT DEPT_ID AS dept_id, DEPT_NAME AS dept_name, MANAGER_ID AS manager_id FROM src_dept"
  }
}
sink {
  Jdbc {
    source_table_name = "sink_dept"
    table = "hr_public.departments"
  }
}
